name: Publish ngx-table-nested library

on:
  push:
    branches: [ "stage" ]
  pull_request:
    branches: [ "stage" ]

jobs:
  PublishLib:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://www.npmjs.com/notpilots/'

      - name: Install dependencies
        run: |
          npm install --no-optional

      - name: Install angular cli
        run: |
          npm install -g @angular/cli

      - name: Build library
        run: |
          ng build ngx-table-nested

      - name: Move to folder
        run: |
          cd ./dist/ngx-table-nested

      - name: Run ci lib
        run: |
          npm ci

      - name: Publish to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
